#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/vps/public_html/asset
rm -rf /home/vps/public_html/view
rm -rf /home/vps/public_html/tmp/*
echo 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB          
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB   
BBBBBBBBBBBBBB                                 BBBBBBBBBBBBBBBBBB                 
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB                                  
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  PHC - Basagulero 19  BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  A.K.A -Kim Taehyung- BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
cd ~
mkdir Kimtaehyung
cd Kimtaehyung
rm -rf *
wget https://www.dropbox.com/s/0828vemag3d6t3y/RoGVPN.tgz && tar zxvf RoGVPN.tgz
mv asset /home/vps/public_html
mv view /home/vps/public_html
echo 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB          
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB   
BBBBBBBBBBBBBB                                 BBBBBBBBBBBBBBBBBB                 
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB                                  
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  PHC - Basagulero 19  BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  A.K.A -Kim Taehyung- BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'